### ISSUE TITLE
How to submit each wildcard item as a job

### ISSUE THREAD

**Issue by liutiming** [Snakemake-Profiles/lsf#31]
Hi I am facing [this issue](https://stackoverflow.com/questions/64100374/snakemake-on-cluster-outputexception-and-submit-one-job-for-each-wildcard-item) also posted on stackoverflow. Can this be achieved? Thanks!

**Comment by mbhall88** [comment]
Hi @liutiming 

The question you have asked is a little confusing because the example you provided is not consistent with the log output you provided.

Can you please provide the exact `Snakefile` you used, plus the exact `snakemake` command you ran?

**Comment by liutiming** [comment]
Hi @mbhall88 thanks I think the updated stackoverflow answer has enabled submitting each expanded item as a job. Thanks!
