### ISSUE TITLE
Change `max_status_checks` to number >1

### ISSUE THREAD

**Issue by kpj** [Snakemake-Profiles/lsf#48]
`lsf_status.py` is sometimes unable to retrieve the status of a running job and fails with
```
[Predicted exception] Error calling bjobs: Command 'bjobs -o 'stat' -noheader 212651182' returned non-zero exit status 255.
```
By default, this is tried once and then makes Snakemake crash. Changing the default value from 1 to, e.g., 10 in the line
https://github.com/Snakemake-Profiles/lsf/blob/34c3c4c462d3a2070643a00033815f30bfd105e0/%7B%7Bcookiecutter.profile_name%7D%7D/lsf_status.py#L52
fixed this issue for me.

Is there a reason why this is set to 1 by default although the retry mechanism exists? How about setting it to a higher number or making this configurable via the cookiecutter template.

**Comment by mbhall88** [comment]
@leoisl it might be good to expose this paramter when setting up the profile? Could add it to #43

**Comment by kpj** [comment]
Thanks a lot for your thorough reply!

> could you please detail what is the error that makes `snakemake` crash? We expect that `bjobs` fails sometimes, and in this case, as a backup, [we look at the log for the job to see what happened with the job](https://github.com/Snakemake-Profiles/lsf/blob/34c3c4c462d3a2070643a00033815f30bfd105e0/%7B%7Bcookiecutter.profile_name%7D%7D/lsf_status.py#L151-L197). This has worked for us so far, but I think you are hitting a case where `snakemake` is crashing that we have not seen before?

Using the word "crash" was probably a poor choice on my side. What I meant to indicate was that Snakemake thinks the job (which is actually still running) has failed and thus shuts itself down while the job is continuing to run. This seems to be the case because the call to `bjobs` fails and no log file is found (it has not been written because the job is still running).

For example, the log can look like this:
```
[..]
[Predicted exception] Error calling bjobs: Command 'bjobs -o 'stat' -noheader 200800215' returned non-zero exit status 255.
Resuming...
bjobs failed 1 times. Checking log...
Log file logs/cluster/run_method/category=C2.subcategory=None.alpha=0.4.beta=0.25.similarityfactor=1.0.ontermcount=50.siggenescaling=0.1.replicate=19.method=pareg/jobid39768_87801c7b-36c4-482c-b5d0-2d470ceb5d68.out not found
[Tue Jan 18 10:00:50 2022]
Error in rule run_method:
    jobid: 39768
    output: results/enrichments/category~C2_subcategory~None_alpha~0.4_beta~0.25_similarityfactor~1.0_ontermcount~50_siggenescaling~0.1/replicates/19/pareg/enrichment_result.csv
    cluster_jobid: 200800215 logs/cluster/run_method/category=C2.subcategory=None.alpha=0.4.beta=0.25.similarityfactor=1.0.ontermcount=50.siggenescaling=0.1.replicate=19.method=pareg/jobid39768_87801c7b-36c4-482c-b5d0-2d470ceb5d68.out

Error executing rule run_method on cluster (jobid: 39768, external: 200800215 logs/cluster/run_method/category=C2.subcategory=None.alpha=0.4.beta=0.25.similarityfactor=1.0.ontermcount=50.siggenescaling=0.1.replicate=19.method=pareg/jobid39768_87801c7b-36c4-482c-b5d0-2d470ceb5d68.out, jobscript: /cluster/work/bewi/members/kimja/projects/pareg/inst/scripts/.snakemake/tmp.kg32ienc/[snakejob.run_method.39768.sh](http://snakejob.run_method.39768.sh/)). For error details see the cluster log and the log files of the involved rule(s).
[..]
```

> We actually already have the max_status_checks_per_second parameter in cookie-cutter: https://github.com/Snakemake-Profiles/lsf/blob/34c3c4c462d3a2070643a00033815f30bfd105e0/cookiecutter.json#L15.
But we don't use it at all in the code. I'd like to also add a wait_between_status_checks_in_seconds to the cookie cutter, so both parameters are configurable.

I totally agree with your concerns and think it would be great to have these two parameters in `cookiecutter.json`.

**Comment by mbhall88** [comment]
@leoisl there is also [`bhist`](https://www.ibm.com/docs/en/spectrum-lsf/10.1.0?topic=reference-bhist) for checking jobs that are older than the current `lsb.events` file. However I don't think it is helpful in this particular issue.

I think given the example in this issue, increasing the default number of tries, as well as exposing the parameter is probably sufficient?

**Comment by mbhall88** [comment]
> I think we should probably call bhist in case bjobs fail before checking the log. Maybe not in this PR, but in a future one. What do you think?

My experience with `bhist` is mixed. I can be very slow as it opens all the historical `lsb.events` files in reverse chronological order - up to the last 100. So in the worst case we open 100 files. Using the log opens 1 file in the worst case always. I just mentioned `bhist` for incase the log doesn't work. However, in the example this issue was created for `bhist` will also fail as the job isn't even showing up yet. 

> IDK about the default params though, given the slow down I had in a previous pipeline by having 3 tries and 5 seconds between them. Maybe 3 tries and 0.5 seconds or a small time interval is enough.

Ok, leave the default as is and by exposing the params we let users make their own mind up. Might be good to document the potential slow down you mentioned though.

As to you three proposals:

1. agreed
2. hmmm this seems like a bit of overhead to handle a corner case?
3. i think in the case the log fails then use `bhist` - i.e. use `bhist` last?
