### ISSUE TITLE
Remove `default_mem_mb` from the cookie-cutter

### ISSUE THREAD

**Issue by leoisl** [Snakemake-Profiles/lsf#49]
See https://github.com/Snakemake-Profiles/lsf/issues/45#issuecomment-1097459073 and https://github.com/Snakemake-Profiles/lsf/issues/45#issuecomment-1098196847

**Comment by mbhall88** [comment]
and #41

**Comment by leoisl** [comment]
Sorry, I embarrassingly had not fully understood `snakemake --profile` parameter although I contribute to this project :( . After re-reading it and playing with some directives in the `config.yaml`, I realised we can actually specify not only default `mem_mb`, but also `disk_mb` and `tmpdir`. Closing this in favour of https://github.com/Snakemake-Profiles/lsf/issues/50
