### ISSUE TITLE
BsubInvocation Error 

### ISSUE THREAD

**Issue by suhridbuddha** [Snakemake-Profiles/lsf#63]
I am trying to select some specific nodes on lsf cluster by making a new cluster.json file:

```
{
    "__default__": {
        "queue": "normal",
        "nodes": "lz-gpu lf-gpu ln-gpu lx-gpu ly-gpu ll-gpu",
        "extra": "",
        "threads": 4  # Default thread count, can be overridden per rule
    }
}

```

But i am getting this error?

File "/home/ryanr2/data/anaconda3/envs/sopa/lib/python3.10/subprocess.py", line 526, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command 'bsub -M 200 -n 1 -R 'select[mem>200] rusage[mem=200] span[hosts=1]' -W 300 -o "logs/cluster/patch_segmentation_baysor/index=53/jobid55_6637d0e7-670b-4ba2-ad88-3580dba86228.out" -e "logs/cluster/patch_segmentation_baysor/index=53/jobid55_6637d0e7-670b-4ba2-ad88-3580dba86228.err" -J "patch_segmentation_baysor.index=53" -q normal /lila/data/chanjlab/ryanr2/sopa/workflow/.snakemake/tmp.5z0azw4k/snakejob.patch_segmentation_baysor.55.sh' returned non-zero exit status 255.

any idea?

**Comment by mbhall88** [comment]
The cluster.json functionality has been deprecated for a long time. Please follow [these instructions](https://github.com/Snakemake-Profiles/lsf?tab=readme-ov-file#non-standard-rule-specific-cluster-resource-settings) to achieve what you're trying.

**Comment by dlaehnemann** [comment]
Also, for more flexibility with regard to resource specifications, I can recommend switching to `snakemake >=8.10.7` and the new [lsf remote executor plugin](https://snakemake.github.io/snakemake-plugin-catalog/plugins/executor/lsf.html).
